<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Admin
 * Date: 10/11/12
 * Time: 11:42 PM
 * To change this template use File | Settings | File Templates.
 */


$media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imageLink = $media."wysiwyg/j0435878_-_Copy.jpg";
$firstCat = $this->getMarketplaceurl();
?>

<div id="content_menu" class="clearfix">
    <ul class="home-list-menu">
        <li class="item1"><a class="overlay" href="<?php echo $firstCat; ?>">&nbsp;</a><span><img src="<?php echo $imageLink; ?>" alt="" /></span>
            <h3 class="title-font"><a title="Marketplace" href="">Marketplace</a></h3>
        </li>
        <li class="item2"><a class="overlay" href="#">&nbsp;</a><span><img src="<?php echo $imageLink; ?>" alt="" /></span>
            <h3 class="title-font"><a title="Directory" href="#">Directory</a></h3>
        </li>
        <li class="item3"><a class="overlay" href="#">&nbsp;</a><span><img src="<?php echo $imageLink; ?>" alt="" /></span>
            <h3 class="title-font"><a title="Community" href="#">Community</a></h3>
        </li>
        <li class="item4"><a class="overlay" href="#">&nbsp;</a><span><img src="<?php echo $imageLink; ?>" alt="" /></span>
            <h3 class="title-font"><a title="Competitions" href="#">Competitions</a></h3>
        </li>
        <li class="item5"><a class="overlay" href="#">&nbsp;</a><span><img src="<?php echo $imageLink; ?>" alt="" /></span>
            <h3 class="title-font"><a title="Sell With Us" href="#">Sell With Us</a></h3>
        </li>
    </ul>
</div>
