<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
 <?php $posts = $this->getPosts(); ?>
<?php $currentCat = $this->getCategory(); ?>

<div class="page-title">
    <h1><?php echo $currentCat->getData('title'); ?></h1>
</div>
<div class="toolbar">&nbsp;</div>
<?php if (count($posts)): ?>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div class="postTitle">
                <h3><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>
<!--                <h3>--><?php //echo $post->getCreatedTime(); ?><!--</h3>-->
            </div>
            <div class="post-image"></div> <!-- This is hardcode -->
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>

            <?php echo $this->getBookmarkHtml($post) ?>

            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
            </div>
        </div>
    <?php endforeach; ?>
 <?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php else: ?>  
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>
