<?php
/**
 * Date: 10/24/12
 * Time: 10:15 PM
 */

?>

<div id="directory-welcome">
    <div id="welcome-content">
        <div class="page-title"><h1>welcome to the directory!</h1></div>
        <p>Enjoy searching through our extensive directory to find all vegetarian and vegan services. Everything from holidays, dating or find your local social group!</p>
    </div>

    <form action="#" name="search-directory">
        <p><label>Search (restaurant, italian, hotel, etc)</label>
        <input class="input-text" type="text" name="directory-search" /></p>
		
        <p><label>Near (city, country)</label>
        <input class="input-text" type="text" name = "directory-near"/></p>
    </form>
</div>