<?php $_shipment = $this->getShipment() ?>
<?php $_order    = $this->getOrder() ?>
<?php if ($_shipment && $_order): ?>

<table cellpadding="0" cellspacing="0" border="0" width="100%" class="table">
    <tr align="center">
        <th style="border: 1px solid #000000;"><strong>Product Name</strong></th>
        <th style="border: 1px solid #000000;"><strong>SKU</strong></th>
        <th style="border: 1px solid #000000;"><strong>Quantity</strong></th>
    </tr>
    <?php $i=0; foreach ($_shipment->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
        <tr <?php echo ($i % 2 === 0 ? 'class="even"' : '')?>>
            <td style="border: 1px solid #000000;"><?php echo $_item->getName()?></td>
            <td style="border: 1px solid #000000;"><?php echo $_item->getSku()?></td>
            <td style="border: 1px solid #000000;" align="center"><?php echo number_format($_item->getQty(), 0)?></td>
        </tr>
    <?php endforeach;?>
    
    <tr class="last">
        <td colspan="3">&nbsp;</td>
    </tr>    
</table>
<?php endif;?>