<?php $_invoice = $this->getInvoice() ?>
<?php $_order   = $this->getOrder() ?>
<?php if ($_invoice && $_order): ?>

<table cellpadding="0" cellspacing="0" border="0" width="100%" class="table">
    <tr align="center">
        <th style="border: 1px solid #000000;"><strong>Product Name</strong></th>
        <th style="border: 1px solid #000000;"><strong>SKU</strong></th>
        <th style="border: 1px solid #000000;"><strong>Quantity</strong></th>
        <th style="border: 1px solid #000000;"><strong>Price</strong></th>
        <th style="border: 1px solid #000000;"><strong>Subtotal</strong></th>
    </tr>
    <?php $i=0; foreach ($_invoice->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
        <tr <?php echo ($i % 2 === 0 ? 'class="even"' : '')?>>
            <td style="border: 1px solid #000000;"><?php echo $_item->getName()?></td>
            <td style="border: 1px solid #000000;"><?php echo $_item->getSku()?></td>
            <td style="border: 1px solid #000000;" align="center"><?php echo number_format($_item->getQty(), 0)?></td>
            <td style="border: 1px solid #000000;padding:3px 9px" align="right" ><?php echo $_order->formatPrice($_item->getPrice())?></td>
            <td style="border: 1px solid #000000;padding:3px 9px" align="right" ><?php echo $_order->formatPrice($_item->getPrice() * $_item->getQty())?></td>
        </tr>
    <?php endforeach;?>
    
    <tr class="last">
        <td colspan="5">&nbsp;</td>
    </tr>    

    <tbody class="total">
        <?php echo $this->getChildHtml('invoice_totals')?>
    </tbody>
</table>
<?php endif;?>