<?php
	$selectedShipping = Mage::getSingleton('checkout/cart')
				->getQuote()
				->getShippingAddress()
				->getShippingMethod();
	$selectedShipping = str_replace('dropshipping_','',$selectedShipping);
	$selectedShippings = explode('|',$selectedShipping);
?>
<div class="shipping">
    <h2><?php echo $this->__('Estimate delivery price') ?></h2>
    <div class="shipping-form">
       <form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-zip-form">
            <p><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
            <ul class="form-list">
                <li>
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
                    </div>
                </li>
            <?php //if($this->getStateActive()): ?>
                <li>
                    <label for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"' ?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>' ?><?php echo $this->__('Region') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                       <script type="text/javascript">
                       //<![CDATA[
                           $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
                       //]]>
                       </script>
                       <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getEstimateRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                   </div>
                </li>
            <?php //endif; ?>
            <?php if($this->getCityActive()): ?>
                <li>
                    <label for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
                    </div>
                </li>
            <?php endif; ?>
                <li>
                    <label for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Post Code') ?></label>
                    <div class="input-box">
                        <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
                    </div>
                </li>
            </ul>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Get a Quote') ?>" onclick="coShippingMethodForm.submit()" class="button"><span><span><?php echo $this->__('Get a Quote') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
        //]]>
        </script>

        <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        <?php  ?>
        <form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>">
            <dl class="sp-methods">
                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
					<?php if($code == 'dropshipping'):?>
						<?php 
							$firtRate = reset($_rates);
							$shippingRatesByVendors = $firtRate->getShippingRatesByVendors();
						?>
						<?php if(!empty($shippingRatesByVendors)):?>
							<script>
								shippingVendor = {};
							</script>
							<?php foreach($shippingRatesByVendors as $vendor):?>
							<script>shippingVendor[<?php echo $vendor['vendor']->getId()?>] = "";</script>
							<dt>
								<?php echo $vendor['vendor']->getVendorName()?>
							</dt>
							<dd>
								<ul>
									<?php foreach($vendor['shipping_methods'] as $r):?>
										<?php $r->setCode('v'.$vendor['vendor']->getId().'_'.$r->getCarrier().'_'.$r->getMethod())?>
										<li>
											
											<input <?php if(in_array($r->getCode(),$selectedShippings)) echo 'checked="checked"'?> vendor_id="<?php echo $vendor['vendor']->getId()?>" id="s_method_<?php echo $r->getCode() ?>" name="shipping_method_by_vendor[<?php echo $vendor['vendor']->getId()?>]" type="radio" value="<?php echo $r->getCode() ?>" class="validate-one-required-by-name radio shipping_method_by_vendor"/>
											<label for="s_method_<?php echo $r->getCode() ?>"><?php echo $r->getCarrierTitle().' - '. $r->getMethodTitle() ?>
											<?php $_excl = $this->getShippingPrice($r->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
											<?php $_incl = $this->getShippingPrice($r->getPrice(), true); ?>
											<?php echo $_excl; ?>
											<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
												(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
											<?php endif; ?>
											</label>
										</li>
									<?php endforeach;?>
								</ul>
							</dd>
							<?php endforeach;?>
							<input name="estimate_method" id="estimate_method" type="hidden" value=""/>
							<script type="text/javascript">
								//<![CDATA[
								$$('input.shipping_method_by_vendor').each(function(el){
									Event.observe(el, 'click', function(){
										if (el.checked == true) {
											var getShippingCode = el.getValue();
											var vendorId = el.getAttribute('vendor_id');
											shippingVendor[vendorId] = el.getValue();
											var shippingSelector = 'dropshipping_';
											var shippingSelected = [];
											for(var v in shippingVendor){
												shippingSelected.push(shippingVendor[v]);
											}
											shippingSelector += shippingSelected.join('|');
											$('estimate_method').setValue(shippingSelector);
											//console.log(shippingSelector);
										}
									});
								});
								//]]>
							</script>
						<?php endif;?>
					<?php endif;?>
                <?php endforeach; ?>
            </dl>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Update Total') ?>" class="button" name="do" value="<?php echo $this->__('Update Total') ?>"><span><span><?php echo $this->__('Update Total') ?></span></span></button>
            </div>
        </form>
        <?php endif; ?>
        <script type="text/javascript">
        //<![CDATA[
            var coShippingMethodForm = new VarienForm('shipping-zip-form');
            var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

            coShippingMethodForm.submit = function () {
                var country = $F('country');
                var optionalZip = false;

                for (i=0; i < countriesWithOptionalZip.length; i++) {
                    if (countriesWithOptionalZip[i] == country) {
                        optionalZip = true;
                    }
                }
                if (optionalZip) {
                    $('postcode').removeClassName('required-entry');
                }
                else {
                    $('postcode').addClassName('required-entry');
                }
                return VarienForm.prototype.submit.bind(coShippingMethodForm)();
            }
        //]]>
        </script>
    </div>
</div>
