<?php
/**
 * Date: 11/26/12
 * Time: 10:51 PM
 */

$helper = Mage::helper('planet');
?>
<div class="toolbar">&nbsp;</div>
<div id="top-category" class="clearfix marketplace-category">
    <?php echo $this->getToolbarHtml() ?>
    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>

    <?php $currentCategory = Mage::registry('current_category') ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('marketplace-topcontent')->toHtml(); ?>
 	<div id="content_menu" class"clearfix">
    <ul class="home-list-menu">
        <li class="item3">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/food.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Vegan_burger_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/food.html">Food</a></h3>
        </li>
        <li class="item2">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/drinks.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Drink_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/drinks.html">Drinks</a></h3>
        </li>
        <li class="item4">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/beauty.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/beauty_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/beauty.html">Beauty</a></h3>
        </li>
        <li class="item5">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/confectionery.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Confectionary_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/confectionery.html">Confectionery</a></h3>
        </li>
        <li class="item3">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/health.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Health_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/health.html">Health</a></h3>
        </li>
        <li class="item4">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/shoes.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Shoes_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/shoes.html">Shoes</a></h3>
        </li>
        <li class="item1">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/book-store.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Books_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/book-store.html">Books</a></h3>
        </li>
        <li class="item3">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/home.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/home_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/home.html">Home</a></h3>
        </li>
        <li class="item5">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/petcare.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Petcare_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/petcare.html">Petcare</a></h3>
        </li>
        <li class="item2">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/clothing.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/clothing_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/clothing.html">Clothing </a></h3>
        </li>
        <li class="item3">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/baby-kids.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Baby_Toys_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/baby-kids.html">Baby & Kids</a></h3>
        </li>
        <li class="item2">            
                <a class="overlay"><a href="http://armadillo.planet-v.co.uk/gifts.html"><img src="http://armadillo.planet-v.co.uk/media/resized/catalog/category/Giftsets_172.jpg" /></a>
                <h3 class="title-font"><a href="http://armadillo.planet-v.co.uk/gifts.html">Gifts</a></h3>
        </li>
                    </ul>
    </div>

            
            
        </li>
    </ul>
	</div>
