<?php
/**
 * Date: 11/26/12
 * Time: 10:51 PM
 */

$helper = Mage::helper('planet');
?>
<div class="toolbar">&nbsp;</div>
<div id="top-category" class="clearfix marketplace-category">
    <?php echo $this->getToolbarHtml() ?>
    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>

    <?php $currentCategory = Mage::registry('current_category') ?>
    <?php if (count($_categories) > 0): ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('marketplace-topcontent')->toHtml(); ?>
    <ul class="marketplace-grid">
        <?php foreach($_categories as $_category): ?>
        <?php if ($_category->getName() == 'marketplace') continue; ?>
        <li>
            <div class="cat-item">
                <?php $cat = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                <?php $imgUrl = $helper->resizeImg('catalog/category/'.$cat->getData('thumbnail'),189,190) ?> <!--resize image-->
                <!--                        --><?php //var_dump($imgUrl); die; ?>
                <div class="cat-image"><a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php if ($cat->getData('thumbnail')): ?><img src="<?php echo $imgUrl ?>" /><?php endif ?></a></div>
                <h3 class="cat-name"><a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName() ?></a></h3>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>

