<?php
/**
 * @category    design
 * @package     provendors_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
$item = $this->getItem();
// $product = $item->getProduct();
$product = Mage::getModel('catalog/product')->load($item->getProductId());

$isVisibleProduct = $product->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

$productName = $this->htmlEscape($this->getProductName());
$productUrl = $this->hasProductUrl() ? $this->getProductUrl() : 'javascript:void(0)';

$productDescriptionMaxLength = 140;
$productShortDescription = Mage::helper('core/string')->truncate($product->getShortDescription(), $productDescriptionMaxLength, '...', $remainder = '', false);
?>
<td class="removed"><a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove2"><?php echo $this->__('Remove item')?></a></td>
<td class="img-product">
	<a href="<?php echo $productUrl ?>" title="<?php echo $productName ?>" class="product-image">
		<img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" alt="<?php echo $productName ?>" />
	</a>
</td>
<td class="cart-product-details">
	<div class="product-name">
		<p><a href="<?php echo $productUrl ?>"><?php echo $productName ?></a></p>
		<!--p><?php echo $productShortDescription ?></p-->
	</div>
	<?php if ($options = $this->getOptionList()): ?>
	<dl class="item-options">
		<?php foreach ($options as $_option) : ?>
		<?php $formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
		<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
		<dd<?php if (isset($formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $formatedOptionValue['value'] ?>
			<?php if (isset($formatedOptionValue['full_view'])): ?>
			<div class="truncated_full_value">
				<dl class="item-options">
					<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
					<dd><?php echo $formatedOptionValue['full_view'] ?></dd>
				</dl>
			</div>
			<?php endif; ?>
		</dd>
		<?php endforeach; ?>
	</dl>
	<?php endif;?>
	<?php if ($messages = $this->getMessages()): ?>
		<?php foreach ($messages as $message): ?>
		<p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></p>
		<?php endforeach; ?>
	<?php endif; ?>
	<?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
		<?php echo $addtInfoBlock->setItem($item)->toHtml() ?>
	<?php endif;?>
</td>

<td class="a-center qty">
	<input name="cart[<?php echo $item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" />
</td>

<?php if ($canApplyMsrp): ?>
	<td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
		<span class="cart-price">
			<span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
			<?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
			<a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
			<script type="text/javascript">
				Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__('What\'s this?') ?>");
			</script>
		</span>
	</td>

<?php else: ?>

	<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
	<td class="price-shop">
		<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
		<?php else: ?>
			<span class="cart-price">
		<?php endif; ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()); ?>
			<?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()) ?>
			<?php endif; ?>

		</span>


		<?php if (Mage::helper('weee')->getApplied($item)): ?>

			<div class="cart-tax-info" id="eunit-item-tax-details<?php echo $item->getId(); ?>" style="display:none;">
				<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
					<?php endforeach; ?>
				<?php endif; ?>
			</div>

			<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
					<span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()); ?></span>
				</div>
			<?php endif; ?>
		<?php endif; ?>
	</td>
	<?php endif; ?>
	<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
	<td>
		<?php $_incl = $this->helper('checkout')->getPriceInclTax($item); ?>
		<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
		<?php else: ?>
			<span class="cart-price">
		<?php endif; ?>

			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php echo $this->helper('checkout')->formatPrice($_incl+$item->getWeeeTaxAppliedAmount()); ?>
			<?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($_incl-$item->getWeeeTaxDisposition()) ?>
			<?php endif; ?>

		</span>
		<?php if (Mage::helper('weee')->getApplied($item)): ?>

			<div class="cart-tax-info" id="unit-item-tax-details<?php echo $item->getId(); ?>" style="display:none;">
				<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
					<?php endforeach; ?>
				<?php endif; ?>
			</div>

			<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
					<span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$item->getWeeeTaxAppliedAmount()); ?></span>
				</div>
			<?php endif; ?>
		<?php endif; ?>
	</td>
	<?php endif; ?>
<?php endif; ?>

<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
<td class="a-right total-price">
	<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
		<span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
	<?php else: ?>
		<span class="cart-price">
	<?php endif; ?>

		<?php if ($canApplyMsrp): ?>
			<span class="cart-msrp-subtotal">--</span>
		<?php else: ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()+$item->getWeeeTaxAppliedRowAmount()+$item->getWeeeTaxRowDisposition()); ?>
			<?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()) ?>
			<?php endif; ?>
		<?php endif; ?>

	</span>
	<?php if (Mage::helper('weee')->getApplied($item)): ?>

		<div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $item->getId(); ?>" style="display:none;">
			<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
				<?php endforeach; ?>
			<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
				<?php endforeach; ?>
			<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>

		<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()+$item->getWeeeTaxAppliedRowAmount()+$item->getWeeeTaxRowDisposition()); ?></span>
			</div>
		<?php endif; ?>
	<?php endif; ?>
</td>
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
<td>
	<?php $_incl = $this->helper('checkout')->getSubtotalInclTax($item); ?>
	<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
		<span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
	<?php else: ?>
		<span class="cart-price">
	<?php endif; ?>

		<?php if ($canApplyMsrp): ?>
			<span class="cart-msrp-subtotal">--</span>
		<?php else: ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php echo $this->helper('checkout')->formatPrice($_incl+$item->getWeeeTaxAppliedRowAmount()); ?>
			<?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($_incl-$item->getWeeeTaxRowDisposition()) ?>
			<?php endif; ?>
		<?php endif; ?>

	</span>


	<?php if (Mage::helper('weee')->getApplied($item)): ?>

		<div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $item->getId(); ?>" style="display:none;">
			<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
				<?php endforeach; ?>
			<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
				<?php endforeach; ?>
			<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
					<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>

		<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $item->getId(); ?>', this, 'cart-tax-total-expanded');">
				<span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$item->getWeeeTaxAppliedRowAmount()); ?></span>
			</div>
		<?php endif; ?>
	<?php endif; ?>
</td>
<?php endif; ?>
