<?php $_invoice = $this->getInvoice() ?>
<?php $_order   = $this->getOrder() ?>
<?php if ($_invoice && $_order): ?>

<table cellpadding="0" cellspacing="0" border="0" width="100%" class="table">
    <tr>
        <th>Product Name</th>
        <th>SKU</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Subtotal</th>
    </tr>
    <?php $i=0; foreach ($_invoice->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
        <tr <?php echo ($i % 2 === 0 ? 'class="even"' : '')?>>
            <td><?php echo $_item->getName()?></td>
            <td><?php echo $_item->getSku()?></td>
            <td align="center"><?php echo number_format($_item->getQty(), 0)?></td>
            <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_item->getPrice())?></td>
            <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_item->getPrice() * $_item->getQty())?></td>
        </tr>
    <?php endforeach;?>
    
    <tr class="last">
        <td colspan="5">&nbsp;</td>
    </tr>    

    <tbody class="total">
        <?php echo $this->getChildHtml('invoice_totals')?>
    </tbody>
</table>
<?php endif;?>