body,td,th { font-family:arial;color:#666;font-size:12px; }    
a {color:#268ecd}
a img {border:0;}
img {border:0;}
h4 {margin:10px 0;padding:0;color:#333;}
.table {background:#f6f6f6;}
.table th {font-weight:bold;background:#888;border-top:solid 1px #cfcfcf;border-bottom:solid 1px #b8b8b8;border-left:solid 1px #eaeaea;height:34px;color:#FFF;text-align:center;vertical-align:middle}
.table th:first-child, .table table td:first-child {border-left:0;}
.table td {border-left:solid 1px #fbfbfb;padding-left:9px;height:30px;vertical-align:middle}
.table tr.even {background:#eaeaea}
.table tr.last td {border-bottom:solid 1px #9e9e9e; height:5px; font-size:1px}
.table a {color:#666;text-decoration:none;}
.table a.brand {color:#268ecd;font-weight:bold;}
.table .small {font-size:11px;}
.table tbody.total {background: #fff;}
td.footer h4 {font-size:14px;}