<?php
/**
 * Date: 10/15/12
 * Time: 2:18 AM
 */

?>


    <?php $currentUrl = $this->helper('core/url')->getCurrentUrl(); ?>
    <div id="facebook-like">
        <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="<?php echo $currentUrl ?>" show_faces="false" width="450" font=""></fb:like>
    </div>
    <div class="tweet"><a href="http://twitter.com/share" class="twitter-share-button" data-count="none" data-via="PlanetV4">Tweet</a></div>

</div>
