<?php 
    $_layout = Mage::app()->getLayout();
    $vendor = $this->getVendor();
    $creditmemo = $this->getCreditmemo();
    $vendorOrder = $this->getVendorOrder();
    $order = $this->getOrder();
    $payment_html = $this->getPaymentHtml();
?>
<html>
<body>
<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#ffffff">
    <tr>
        <td align="center"><table cellspacing="0" cellpadding="0" border="0" 
            style="text-align:left">
            <tr>
                <td colspan="2" style="height:5px;background:#2897d4;font-size:0">&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <?php echo $_layout->createBlock('core/template', '', array('template' => 'sm/email/order/email_logo.phtml', 'vendor'=>$vendor))->toHtml() ?>
                    <br/>
                    <?php echo $_layout->createBlock('core/template', '', array('template' => 'sm/email/order/vendor_info.phtml', 'vendor'=>$vendor))->toHtml() ?>
                </td>
                <td align="right" style="padding-top:20px;">
	                <table cellpadding="0" cellspacing="0" 
	                    border="0" style="text-align:left">
	                    <tr>
	                        <td>Creditmemo no</td>
	                        <td>:&nbsp;&nbsp; <?php echo $creditmemo->getIncrementId()?></td>
	                    </tr>
	                    <tr>
	                        <td>Order no</td>
	                        <td>:&nbsp;&nbsp; <?php echo $vendorOrder->getIncrementId()?></td>
	                    </tr>    
	                    <tr><td colspan="2" style="height: 10px;"></td></tr>
	                    <?php echo $_layout->createBlock('core/template', '', array('template' => 'sm/email/order/buyer_info.phtml', 'order'=>$order, 'output_shipping'=>true))->toHtml() ?>
	                </table>
                </td>
            </tr>
            <tr>
                <td colspan="2" valign="top">
                <h3 style="padding:10px 20px;margin:0;color:#000;text-transform:uppercase;">CREDITMEMO</h3></td>
            </tr>
            <tr><td colspan="2" style="height: 20px;"></td></tr>
        </table></td>
    </tr>
</table>            
<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
        <td style="padding-bottom:10px;" class="pdf-items-table">
            <br/>
            <?php 
                $params = array('area'=>'frontend', 
                        'handle'=>'vendors_sales_email_order_creditmemo_items',
                        'creditmemo'=>$creditmemo,
                        'order'=>$order,
                        'payment_html'=>$payment_html,
                        );
            ?>
            <?php echo Mage::helper('smvendors')->getLayoutOutput($params)?>
        </td>
    </tr>
</table>
</body>
</html>