<?php
$helper = Mage::helper('smvendors');
$vendors = Mage::getModel('smvendors/vendor')->getCollection();
$helper = Mage::helper('smvendors')

?>


<div class="page-title">
	<h1><?php echo $this->__('Merchants') ?><span></span></h1>
</div>

<div class="mechant-list">
    <h2>Merchant at planet V</h2>
    <ul>
        <?php foreach($vendors as $vendor): ?>
<!--        Check if vendor has slug or active ?-->
        <?php if ($vendor->getData('vendor_status') == 0 || is_null($vendor->getData('vendor_slug'))) continue;  ?>
        <li>
            <a href="<?php echo $helper->getVendorUrl($vendor) ?>"><span class="mechant-name"><?php echo $vendor->getData('vendor_name') ?></span></a>

            <div class="mechant-description">
                <?php echo $vendor->getData('description') ?>
            </div>
        </li>
        <?php endforeach ?>

    </ul>
</div>
