<?php
/**
 * Date: 10/21/12
 * Time: 11:35 PM
 */
$home_url = Mage::helper('core/url')->getHomeUrl();
?>

<div id="left-col" >
    <ul>
        <li><a href="<?php echo $home_url.'shop-with-us'  ?>"><?php echo $this->__('shop with us') ?></a></li>
        <li><a href="<?php echo $home_url.'delivery' ?>"><?php echo $this->__('delivery') ?></a></li>
        <li><a href="<?php echo $home_url.'return' ?>"><?php echo $this->__('returns') ?></a></li>
        <li><a href="#"><?php echo $this->__('faqs') ?></a></li>
        <li><a href="#"><?php echo $this->__('where is my order') ?></a></li>
        <li><a href="<?php echo $home_url.'contact-us' ?>"><?php echo $this->__('contact us') ?></a></li>
    </ul>
</div>
